### PR TITLE
Move to v1.0.0 of tmdb-java

### PR DESCRIPTION
**Pull request by davidsben**
This series is focused around moving to v1,0.0 of the tmdb-java library (with a view to add certification support for TV shows in a future pull request)

I've updated the test code of scraper-tmdb to be up-to-date with the current state of TMDB and checked that all tests are passing. However I've never used Maven before and completely failed at being able to test my modified plugin with the core TMM program (I kept getting java.lang.IncompatibleClassChangeError errors when trying with Eclipse)

### CODE REVIEW

**Comment by mlaggner** [comment]
thanks for your pull request.
There are (at least) two issues:

a) in your pom.xml you package the old artifact with maven-shade:

```
<include>com.uwetrottmann:tmdb-java</include>
```

you have to change that to the new artifact (`com.uwetrottmann.tmdb2:tmdb-java`)

b) when creating the httpclient, you create a new builder which has no settings from tmm (proxy, timeouts, ...)

```
OkHttpClient.Builder builder = TmmHttpClient.getHttpClient().newBuilder();
builder.addInterceptor(new TmdbInterceptor(this));
return builder.build();
```

unfortunately the copy constructor of OkHttpClient.Builder (Builder(OkHttpClient)) is not visible, so we have two options here:
* copy the relevant code from this constructor into the tmdb scraper
* change our API class TmmHttpClient to create a nice builder for us. (TmmHttpClient.newBuilder())

I'd recommend the later version, because that could be handy for other scrapers too. I'll enhance the API in the next hours while you can improve your pull request

**Comment by mlaggner** [comment]
the commit tinyMediaManager/api-scraper@a07c44d4ee4a71fa0c200b1aa089bd3a5b881f07 provides our preconfigured OkHttpClient.Builder for usage in the scraper. Please use this for creation of the OkHttpClient

**Comment by davidsben** [comment]
I've updated my commit with the fixes to pom.xml as well as to use the newBuilder() routine instead if you would kindly check it again.

**Comment by mlaggner** [comment]
looks good, thanks for your pull request

**Pull request merged**
